apiVersion: dynamodb.aws.upbound.io/v1beta2
kind: Table
metadata:
  annotations:
    meta.upbound.io/example-id: dynamodb/v1beta2/table
  name: example
  namespace: crossplane-system
spec:
  providerConfigRef:
    name: default 
  forProvider:
    attribute:
      - name: UserId
        type: S
      - name: GameTitle
        type: S
      - name: TopScore
        type: S
    billingMode: PROVISIONED
    globalSecondaryIndex:
      - hashKey: GameTitle
        name: GameTitleIndex
        nonKeyAttributes:
          - UserId
        projectionType: INCLUDE
        rangeKey: TopScore
        readCapacity: 10
        writeCapacity: 10
    hashKey: UserId
    rangeKey: GameTitle
    readCapacity: 20
    region: us-east-1
    tags:
      Environment: production
      Name: dynamodb-table-1
    writeCapacity: 20
