apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: crossplane-bucket-argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  forProvider:
    region: us-east-2
  providerConfigRef:
    name: default
