apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-resources
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/devplatformsolutions/crossplane-config.git'
      path: 'resources/aws/s3'
      targetRevision: HEAD
      directory:
        recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
